Proiect/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

Proiect/aplicatie2/urls.py
from django.urls import path
from aplicatie2 import views

app_name = 'companies'

urlpatterns = [
    path('', views.CompaniesView.as_view(), name='lista_companii'),
    path('adaugare/', views.CreateCompaniesView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateCompaniesView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_companies, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_companies, name='activeaza'),]

Proiect/aplicatieJobs/urls.py
from django.urls import path

from aplicatieJobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.JobsView.as_view(), name='lista_jobs'),
    path('adaugare/', views.CreateJobsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateJobsView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_jobs, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_jobs, name='activeaza'),]

Proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path('jobs/', include('aplicatieJobs.urls')),
    path('companies/',include('aplicatie2.urls')),
]

Proiect/aplicatie1/models.py
from django.db import models


class Locations(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=150)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.city} - {self.country}"

Proiect/aplicatie2/models.py
from django.db import models

tipuri_companie = (('SRL', 'S.R.L.'), ('SA', 'S.A.'))
# first is save in data base


# Create your models here.
class Companies(models.Model):
    nume = models.CharField(max_length=100)
    website = models.CharField(max_length=50)
    tip_companie = models.CharField(max_length=10, choices=tipuri_companie)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.nume} - {self.website} - {self.tip_companie}"

Proiect/aplicatieJobs/models.py
from django.db import models


class Jobs(models.Model):
    type = models.CharField(max_length=11)
    url = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=300)
    how_to_apply = models.TextField(max_length=300)

    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.type} - {self.url} - {self.title} - {self.description} - {self.how_to_apply}"

Proiect/aplicatie1/views.py

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie1.models import Locations


class LocationsView(LoginRequiredMixin, ListView):
    model = Locations
    template_name = 'aplicatie1/locations_index.html'
    paginate_by = 5


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


@login_required
def delete_location(request, pk):
    Locations.objects.filter(id=pk).update(active=0)
    return redirect('locations:lista_locatii')


@login_required
def activate_location(request, pk):
    Locations.objects.filter(id=pk).update(active=1)
    return redirect('locations:lista_locatii')

Proiect/aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie2.models import Companies


class CompaniesView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'aplicatie2/companies_index.html'
    paginate_by = 5


class CreateCompaniesView(LoginRequiredMixin, CreateView):
    model = Companies
    fields = ['nume', 'website', 'tip_companie']
    template_name = 'aplicatie2/companies_form.html'

    def get_success_url(self):
        return reverse('companies:lista_companii')


class UpdateCompaniesView(LoginRequiredMixin, UpdateView):
    model = Companies
    fields = ['nume', 'website', 'tip_companie']
    template_name = 'aplicatie2/companies_form.html'

    def get_success_url(self):
        return reverse('companies:lista_companii')


@login_required
def delete_companies(request, pk):
    Companies.objects.filter(id=pk).update(active=0)
    return redirect('companies:lista_companii')


@login_required
def activate_companies(request, pk):
    Companies.objects.filter(id=pk).update(active=1)
    return redirect('companies:lista_companii')

Proiect/aplicatieJobs/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatieJobs.models import Jobs


class JobsView(LoginRequiredMixin, ListView):
    model = Jobs
    template_name = 'aplicatieJobs/jobs_index.html'
    paginate_by = 5


class CreateJobsView(LoginRequiredMixin, CreateView):
    model = Jobs
    fields = ['type', 'url', 'title', 'description', 'how_to_apply']
    template_name = 'aplicatieJobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_jobs')


class UpdateJobsView(LoginRequiredMixin, UpdateView):
    model = Jobs
    fields = ['type', 'url', 'title', 'description', 'how_to_apply']
    template_name = 'aplicatieJobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_jobs')


@login_required
def delete_jobs(request, pk):
    Jobs.objects.filter(id=pk).update(active=0)
    return redirect('jobs:lista_jobs')


@login_required
def activate_jobs(request, pk):
    Jobs.objects.filter(id=pk).update(active=1)
    return redirect('jobs:lista_jobs')


Proiect/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

Proiect/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'locations:adauga' %}" class="btn btn-success">Adauga locatie</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>City</th>
            <th>Country</th>
            <th>Stare</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in locations_list %}
            <tr>
                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country }}</td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>
                <td>
                    <a href="{% url 'locations:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'locations:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'locations:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
                <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}
        </span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

Proiect/templates/aplicatie2/companies_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">

        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit" style="background:green;color:white;">Salveaza</button>
    </form>
{% endblock %}

Proiect/templates/aplicatie2/companies_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'companies:adauga' %}" class="btn btn-success">Adauga locatie</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Nume</th>
            <th>Website</th>
            <th>Tip Companie</th>
            <th>Stare</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in companies_list %}
            <tr>
                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                <td>{{ item.nume }}</td>
                <td>{{ item.website }}</td>
                <td>{{ item.tip_companie }}</td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>
                <td>
                    <a href="{% url 'companies:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'companies:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'companies:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
                <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}
        </span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

Proiect/templates/aplicatieJobs/jobs_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="col-md-10">
        {% for field in form %}
          <div class="col-md-10">
            {{ field.label }}
             <div class="col-md-20">
            {{ field }}<br>

              </div>
               </div>
        {% endfor %}
         </div>
         <div>
        <button type="submit">Salveaza</button>
         </div>
    </form>
{% endblock %}

Proiect/templates/aplicatieJobs/jobs_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'jobs:adauga' %}" class="btn btn-success">Add job</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Type</th>
            <th>url</th>
            <th>Title</th>
            <th>Description</th>
            <th>How to apply</th>
            <th>Stare</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in jobs_list %}
            <tr>
                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                <td>{{ item.type }}</td>

                <td>{{ item.url }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.how_to_apply }}</td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>
                <td>
                    <a href="{% url 'jobs:modifica' item.id %}" class="btn btn-success">Change</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'jobs:sterge' item.id %}" class="btn btn-danger">Delete</a>
                    {% else %}
                        <a href="{% url 'jobs:activeaza' item.id %}" class="btn btn-info">On</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
                <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}
        </span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

Proiect/templates/base.html
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                <a class="btn" href="{% url 'jobs:lista_jobs' %}">Jobs</a>
                <a class="btn" href="{% url 'logout' %}">Logout</a>


            </nav>
        </div>
    </div>
</div>
<div class="col-md-12">
    {% block content %}
    {% endblock %}
</div>
</body>

</html>